name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - run: playwright install
      - run: playwright install-deps

      - run: pytest --browser ${{ matrix.browser }} --screenshot only-on-failure --video retain-on-failure --html=report.html --self-contained-html
        env:
          SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
          BASE_URL: https://www.saucedemo.com

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-${{ matrix.browser }}
          path: |
            report.html
            test-results/name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - run: playwright install
      - run: playwright install-deps

      - run: pytest --browser ${{ matrix.browser }} --screenshot only-on-failure --video retain-on-failure --html=report.html --self-contained-html
        env:
          SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
          BASE_URL: https://www.saucedemo.com

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-${{ matrix.browser }}
          path: |
            report.html
            test-results/

# Note:
# YAML File anatomy:
# name   → display name in Actions tab
# on     → trigger — when to run
# jobs   → units of work
# steps  → commands inside each job
# uses   → pre-built actions from marketplace
# run    → shell commands you write

# CI runner is a fresh machine — missing Linux system libraries that Chrome needs.
# playwright install chromium       # downloads chromium browser
# playwright install-deps chromium  # installs Linux system deps for it